DataDog/lemur

- .github/CODEOWNERS
This PR updates sets the default code owners of this repository to the network edge team. In practice this is a quality of life improvement that will automatically tag our team for a review any time a new PR is submitted.
Closes [EDGE-1361](https://datadoghq.atlassian.net/browse/EDGE-1361).
> Set default code owners to network edge

- .gitlab-ci.yml
While testing the CI image build process I noticed that two Lemur images were being published: one with the `staging` label, and another with the `prod` label. In this particular scenario where a commit is tagged we only need to publish a single image with the `prod` label. To achieve this the `build-stage-image` stage in the CI has been explicitly disabled for tagged commits.
> Only build prod image for tagged commits

- lemur/certificates/models.py
- lemur/endpoints/models.py
- lemur/endpoints/service.py
- lemur/migrations/versions/44d67c1988a2_.py
- lemur/models.py
- lemur/sources/service.py
- lemur/tests/factories.py
- lemur/tests/test_certificates.py
- lemur/tests/test_endpoints_certificates_assoc.py
This PR introduces the database schema changes required to support modeling the following relationships:
1. many certificates to an endpoint (**_new requirement for adding SNI support_**)
2. many endpoints to a certificate (**_already supported today_**). 
To achieve this relationship, I used the recommend [Association Object](https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#association-object) and [Association Proxy](https://docs.sqlalchemy.org/en/14/orm/extensions/associationproxy.html) patterns described in the official SQLAlchemy documentation. I maintained backward compatibility at existing call sites using [Hybrid Attributes](https://docs.sqlalchemy.org/en/14/orm/extensions/hybrid.html) but added deprecation warnings to notify the users that these should be updated …
> Add many-to-many relationship support between certificates and endpoints

- lemur/endpoints/schemas.py
- lemur/static/app/angular/endpoints/view/view.tpl.html
This PR makes the following high level changes to support displaying all of the certificates attached to an endpoint in the web UI:
1. Updates the endpoints REST API routes so that they return all certificates attached to the endpoint in their JSON response.
2. Updates the angular application to render all certificates attached to the endpoint in the web UI using a nested [list group](https://getbootstrap.com/docs/4.0/components/list-group/). 
**Preview**
Closes [EDGE-1363](https://datadoghq.atlassian.net/browse/EDGE-1364). Requires #5.
> Support displaying SNI certificates to user in web UI

- lemur/certificates/models.py
- lemur/endpoints/models.py
- lemur/migrations/versions/44d67c1988a2_.py
- lemur/models.py
- lemur/tests/test_endpoints_certificates_assoc.py
- Remove the unique constraint which enforces that a given SNI certificate can be associated with an endpoint only once. In AWS for example, it's possible for the same certificate to be associated with an ELBv2 many times. While this is unusual, we should still allow this state to be modeled in the database so it can be handled properly elsewhere. (E.g. a background task which removes unnecessary duplicate certificate attachments.)
- Update the foreign key constraints added in #5 to use cascade deletion behavior. This gives very strong guarantees that when a `Certificate` or `Endpoint` is deleted from the database, the corresponding `EndpointsCertificates` association object will be deleted as well.
- Use `cascade='all,delete-orphan'` on the ORM relationships added in #5. This is required …
> Adjust uniqueness constraints and deletion behavior for endpoints and certificates

- lemur/certificates/cli.py
- lemur/endpoints/service.py
- lemur/tests/test_endpoints.py
The existing query used for fetching endpoints with certificates eligible for rotation is currently throwing an exception and failing:
```python3
>>> Endpoint.query.filter(Endpoint.primary_certificate.replaced.any()).all()
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/hybrid.py", line 898, in __get__
return self._expr_comparator(owner)
File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/hybrid.py", line 1105, in expr_comparator
comparator(owner),
File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/ext/hybrid.py", line 1090, in _expr
return ExprComparator(cls, expr(cls), self)
File "/opt/lemur/lemur/endpoints/models.py", line 129, in primary_certificate
for assoc in self.certificates_assoc:
File …
```
> Fix query used for retrieving endpoints pending rotation

- lemur/certificates/cli.py
If a user requests that all endpoints associated with `certificateA` be rotated and replaced with `certificateB` (see example) then any endpoint which has `certificateA` attached to it as a SNI certificate should be skipped. The reason that this should be the case is because SNI rotation is not supported yet, and if Lemur is instructed to perform a rotation in this case it will yield unexpected results.
Example:
```
/opt/venv/bin/lemur certificate rotate -o "certificateA" -n "certificateB"
```
> Don't allow SNI certificate rotations until it's supported

- lemur/endpoints/models.py
- lemur/endpoints/service.py
- lemur/tests/test_sources.py
In https://github.com/DataDog/lemur/pull/9/commits/cf1d5c57cfdd40dcf85f6bb6ba54731c14a473d8 a regression was inadvertently introduced which was causing the sync source task to fail when updating an existing endpoint. It was not caught because the test cases did not exercise the update path thoroughly enough. This PR addresses both issues.
> Fix update method in endpoints controller

- lemur/plugins/lemur_gcp/plugin.py
**Background**
After releasing the GCP code to production yesterday Bob noticed that cert uploads were failing for GCP with the following error.
```
Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application
```
The call for `google.auth.default()` fails because the api cant find any default credentials for the commercial lemur environment. 
**Solution**
The way I was setting the token before was slightly "hacky",  because I was leaning on Googles ADC pattern to determine how to get the default credentials and then overriding that with the oauth token received from vault.  This PR refactors that logic to use the `google.oauth2.credentials` module, this is actually the method that google recommends …
> Refactor google oauth token logic

- lemur/plugins/lemur_gcp/plugin.py
- lemur/plugins/lemur_gcp/tests/test_plugin.py
For the GCP API you need to have the certificate chain included with the certificate body, as per the [documentation](https://cloud.google.com/load-balancing/docs/ssl-certificates/self-managed-certs#createresource).
> You can choose to include the CA certificate chain in the same file as the certificate. Google Cloud does not validate the certificate chain for you — validation is your responsibility.
This PR fixes the bug of certificates that are uploaded with the GCP Destination having a broken certificate chain.
> [bugfix] fix certificate chain issue with GCP destination

- lemur/plugins/lemur_gcp/certificates.py
- lemur/plugins/lemur_gcp/endpoints.py
- lemur/plugins/lemur_gcp/plugin.py
- lemur/plugins/lemur_gcp/readme.md
- lemur/plugins/lemur_gcp/tests/test_certificates.py
- lemur/plugins/lemur_gcp/tests/test_endpoints.py
This adds support for SNI certificates when listing certificates attached to an endpoint/LB and rotating a cert on an endpoint with multiple certificates. Note, GCP treats the first certificate in its list as the primary and `update_endpoint` is called by Lemur specifically when updating the primary - `replace_sni_certificate` is called by Lemur when replacing the non-primary. The order for `certificates[1:]` attached to a target proxy does not matter.
Changes:
* Fetch metadata for non-primary certificates attached to a target proxy
* Implement `replace_sni_certificate` so Lemur can rotate non-primary certs in addition to just the primary cert
* Remove some unnecessary API calls when setting the certs on a target proxy
> Add SNI support to the GCP source plugin

- lemur/plugins/lemur_gcp/endpoints.py
If the primary cert has the same body as an SNI cert, we may end up replacing the primary. The caller of `update_target_proxy_sni_certs` assumes that the default cert will remain unmodified.
> [bugfix] Only remove SNI certs for GCP SNI rotation

- lemur/plugins/lemur_azure/plugin.py
- lemur/plugins/lemur_azure/tests/test_azure_source.py
This PR contains the rest of the changes that should be required for closing [EDGE-1725](https://datadoghq.atlassian.net/browse/EDGE-1725):
- Add implementations and tests for the `get_certificates` and `get_certificate_by_name` methods in the source plugin.
- Add support for syncing the SSL policy information (e.g. supported ciphers) for endpoints.
- Fixed a minor issue around certificate naming, in particular certificate names in a key vault can't contain the character `*` when uploading wildcard certificates.
I've included some basic test cases in this PR to verify functionality and also deployed this patch to sandbox and verified that an endpoint in Azure could be synced successfully.
> Support syncing certificates and ssl policies in Azure source plugin

- lemur/plugins/lemur_azure/auth.py
- lemur/plugins/lemur_azure/plugin.py
To minimize excessive retrying slowing down source sync operations, this PR updates the Azure plugins to re-use the existing credential generated from Vault where possible.
- If the Azure credential was already generated, then it will be re-used.
- If the credential expired or a valid access token otherwise could not be dispensed, then it will be re-created.
- If a credential does not already exist, one will be created.
Closes [EDGE-1758](https://datadoghq.atlassian.net/browse/EDGE-1758).
> Re-use existing Azure credential where possible

- lemur/plugins/lemur_gcp/certificates.py
- lemur/plugins/lemur_gcp/plugin.py
- lemur/plugins/lemur_gcp/tests/test_plugin.py
Add an option to the plugin so we can upload regional certificates to GCP. Regional certificates are used by internal HTTPs LBs. Since only regional certs can be used with regional HTTPs proxies and global certs with global HTTPs/SSL proxies, we need to scope the entire Destination / Source plugin operations as global or regional. For datacenters with regional resources, we will create another instance of the destination/source plugin with region set. The next PR will add support to the GCP Source plugin for scoping its operations to a region.
> Add region option to GCP destination plugin

- lemur/plugins/lemur_azure/plugin.py
- lemur/plugins/lemur_azure/tests/test_azure_source.py
- lemur/plugins/lemur_gcp/tests/test_plugin.py
- requirements.in
- requirements.txt
At a high level this change adds support for syncing CDN endpoints in the Azure source plugin. This isn't required for automated rotations but gives us additional visibility into endpoints in our Azure environments that may or may not be using Lemur certificates.
Closes [EDGE-1784](https://datadoghq.atlassian.net/browse/EDGE-1784).
> Support discovering Azure CDN endpoints

- lemur/plugins/lemur_gcp/plugin.py
Fixes a bug in the GCP Destination plugin - the GCP API raises an exception type `google.api_core.exceptions.Conflict` instead of `google.api_core.exceptions.AlreadyExists`, e.g. from a stacktrace:
```lemur_1     |   File "/opt/venv/lib/python3.7/site-packages/google/cloud/compute_v1/services/ssl_certificates/transports/rest.py", line 720, in __call__
lemur_1     |     raise core_exceptions.from_http_response(response)
lemur_1     | google.api_core.exceptions.Conflict: 409 POST https://compute.googleapis.com/compute/v1/projects/XXX: The resource XXX already exists
```
I ran into this when doing a source sync, which syncs both certificates and endpoints. If a certificate cannot be found (e.g. by name, serial, etc.), it will be reuploaded.
> Ignore duplicate certificate uploads to GCP

- publish/Dockerfile
This PR updates the base Docker base image to the GBI for Ubuntu focal. The strategy was to let this image "soak" on staging for a while before promoting. After having it run on the Sandbox instance for >2weeks Im confident with promoting this. 
The base metrics for the app (CPU and Memory) has stayed consistent with the baseline on the previous image. Im also confident that none of the core functionality of the app has been affected because we have been doing testing to the Adapter while this image has been on Sandbox.
> Update the docker base image

- lemur/plugins/lemur_azure/plugin.py
- lemur/plugins/lemur_azure/tests/test_azure_dest.py
In [some situations](https://knowledge.digicert.com/generalinformation/digicert-root-and-intermediate-ca-certificate-updates-2023.html), certificate authorities may proactively begin issuing certificates using a new CA certificate. When this occurs with the current implementation of the destination plugin, the name of the renewed certificate uploaded to Key Vault will change. This is an undesirable side effect because it forces operators to reconfigure their Azure endpoints (CDNs, Application Gateways, etc.) to use the new Key Vault path that the renewed certificate was uploaded to.
To circumvent this issue, this PR updates the certificate naming convention so that it is agnostic to the issuing CA certificate. It does this by changing the certificate naming logic to parse the vendor name …
> Use more stable naming for Azure destination plugin

- requirements-tests.txt
- requirements.txt
Bump redis package by 2 minor versions to v4.4.4
Release [notes for 4.4.3](https://github.com/redis/redis-py/releases/tag/v4.4.3) and [4.4.4](https://github.com/redis/redis-py/releases/tag/v4.4.4)
> bump redis for version 4.4.4

- requirements.in
- requirements.txt
Updates the certificate naming convention used for the Cert Orchestration Adapter Destination Plugin
> Bringing in latest Cert Adapter Destination changes

- lemur/common/celery.py
The current Lemur implementation emits a last_success metric per task based on the name of the function the task invokes.  Source based rotation was recently added to stagger when we rotate certificates in different sites, but this had the side effect of having each site's task emitting metrics for last_success that had no differentiating information based on the site.  This could lead to one site's rotation failing for an extended period but having last_success metrics still report healthy rotation when other sites could rotate correctly.  This PR emits these metrics on a per source basis as well now to correctly track last_success on a per site basis.
> Emitting source based last_success metric to track certificate rotation success by source

- lemur/certificates/service.py
The base destination plugin implementation assumes that all destination plugins will have an account number.  This is very AWS centric and doesn't apply to non-AWS plugins.  This results in some validation code that attempts to read the account number from non-aws destination plugins, populates None as the value, and incorrectly uses None as a dictionary key breaking the validation.
By bypassing this validation when there is no account number we can scope the change to AWS only without major refactors to the code.  In the future we may want to make some more extensible validation in case we want to have other inter-destination validations that are provider specific.
> Skipping duplicate account number validation for destination plugins without an account number

- requirements-docs.in
- requirements-docs.txt
- requirements-tests.in
- requirements-tests.txt
- requirements.in
- requirements.txt
Addressing vulnerabilities found in cert_orchestration_adapter, will import new dependencies there after merge.
Package Name: pycryptodomex
Vulnerable Version[s] < 3.19.1
Patched Version: 3.19.1
Package Name: paramiko
Vulnerable Version[s] < 3.4.0
Patched Version: 3.4.0
Package Name: cryptography
Vulnerable Version[s] >= 3.1, < 41.0.6
Patched Version: 41.0.6
Package Name: urllib3
Vulnerable Version[s] <= 1.26.17
Patched Version: 1.26.18
> Increasing Lemur Dependency Versions to Address Vulnerabilities

- .gitlab-ci.yml
Otherwise image signing will fail e.g. with an error such as:
```
Error: artifact reference argument registry.ddbuild.io/lemur:1.0.0-dd.23 does not match image.name field registry.ddbuild.io/lemur:v30311121-b3bb0b49 in Docker metadata file
```
> Ensure prod image is properly tagged

- .campaigns/build_and_push_image.sh
- .campaigns/get_images.sh
- .gitlab-ci.yml
This PR sets up the necessary GitLab jobs that can be invoked automatically by campaigner to periodically rebuild and publish the container images for Lemur.
> Setup auto image building using campaigner

- requirements.in
- requirements.txt
The build is currently failing because `ddtrace` dependency is out of date:
```
Collecting ddtrace==0.53.0 (from lemur==1.2.dev0)
Downloading ddtrace-0.53.0.tar.gz (1.3 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 89.4 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Installing backend dependencies: started
Installing backend dependencies: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'error'
error: subprocess-exited-with-error
× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [83 lines of …
```
> Bump ddtrace dependency

- .gitlab-ci.yml
These test don't provide any additional validation or checking for top of the GBI lite build step so they don't need to be run in such cases.
> Filter out test stage from GBI lite build

- docker/src/lemur.conf.py
Removes the hardcoded key in the lemur.conf file used for local testing.
The key was previously hardcoded to work around an issue where LEMUR_ENCRYPTION_KEYS would rotate, causing DB queries to fail due to a key mismatch. Although this lemur.conf file is only for local testing, it's best to eliminate the practice of hardcoding values. This PR will set the value to match what is upstream.
> updating value for LEMUR_ENCRYPTION_KEYS in local lemur config

- CHANGELOG.rst
- publish/Dockerfile
Upgrade the GBI to Ubuntu 22.04 to use new Python version
Previous GBI Ubuntu 20.04 came with Python 3.8 causing a crash loop due to Python:
```
File "/opt/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
schema = self._generate_schema_inner(obj)
File "/opt/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
return self.match_type(obj)
File "/opt/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
return self._match_generic_type(obj, origin)
File "/opt/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1062, in _match_generic_type
return self._list_schema(self._get_first_arg_or_any(obj))
File …
```
> Upgrade the GBI to Ubuntu 22.04 to use new Python version

- lemur/common/redis.py
Adds a new configuration option `REDIS_USE_SSL` (disabled by default for backward compatibility) that allows Lemur to be configured such that it uses SSL/TLS when connecting to Redis.
> Support SSL for Redis

- .campaigns/build_and_push_image.sh
- .campaigns/get_images.sh
- .gitlab-ci.yml
- lemur/common/celery.py
- lemur/fips.py
- lemur/manage.py
- publish/Dockerfile
- requirements-dev.in
- requirements-dev.txt
- requirements-docs.in
- requirements-docs.txt
- requirements-overrides.txt
- requirements-tests.in
- requirements-tests.txt
- requirements.in
- requirements.txt
- Enable FIPS mode within the application server and celery workers before initialization if `FIPS_ENABLED=true`.
- Create separate image build and release pipelines for FIPS and non-FIPS images. Both images will be periodically re-built with campaigner and GBILite.
- The FIPS images are tagged with the `IS_FIPS=true` label for tracking purposes.
> Add support for FIPS mode

- .campaigns/build_and_push_image.sh
Both FIPS and non-FIPS images will be built against a single release tag to keep the release process simple. As such, if we're building a FIPS image to be tagged `1.0.0-dd.32-fips`, we need to checkout the source code present at the release tag for `1.0.0-dd.32`.
> Fix prod FIPS image build
